SHOW TABLES

-- 그룹바이 예제!

SELECT A.GENDER, 
	AVG(A.CNT_VIST),
	COUNT(A.CNT_VIST)
FROM KOPO_CUSTOMERDATA A
GROUP BY ROLLUP( A.GENDER )

SELECT COUNT(*)
FROM(
	SELECT A.*, B.REGIONNAME
	FROM KOPO_CHANNEL_SEASONALITY_NEW A,
	KOPO_REGION_MST B
	-- ORDER BY A.REGIONID, A.PRODUCT, A.YEARWEEK
)B

SELECT COUNT(*)
FROM KOPO_CHANNEL_SEASONALITY_NEW

-- ----------------------------------------------
--★★★★★★★★★★★★★★★★★★  조인 ★★★★★★★★★★★★★★★★★★
-- -----------------------------------------------
SELECT *
FROM JOIN_REGION_MASTER

SELECT * 
FROM JOIN_KOPO_PRODUCT_VOLUME

INSERT INTO JOIN_KOPO_PRODUCT_VOLUME 
VALUES ('A05','ST0005','202520',6000)

-- INNER  JOIN (키의 교집합만 살린다)
SELECT A.REGIONID,
	-- B.REGIONID AS B_REGIONID,
	B.REGIONNAME,
	A.PRODUCT,
	A.YEARWEEK,
	A.QTY
FROM JOIN_KOPO_PRODUCT_VOLUME A
RIGHT JOIN JOIN_REGION_MASTER B
ON A.REGIONID = B.REGIONID

-- LEFT  JOIN (기준 데이터를 모두 살린다)
SELECT A.REGIONID,
	-- B.REGIONID AS B_REGIONID,
	B.REGIONNAME,
	A.PRODUCT,
	A.YEARWEEK,
	A.QTY
FROM JOIN_KOPO_PRODUCT_VOLUME A
LEFT JOIN JOIN_REGION_MASTER B
ON A.REGIONID = B.REGIONID

-- RIGHT  JOIN (붙이는 우측 데이터를 모두 살린다)
SELECT A.REGIONID,
	-- B.REGIONID AS B_REGIONID,
	B.REGIONNAME,
	A.PRODUCT,
	A.YEARWEEK,
	A.QTY
FROM JOIN_KOPO_PRODUCT_VOLUME A
RIGHT JOIN JOIN_REGION_MASTER B
ON A.REGIONID = B.REGIONID


-- FULL OUTER JOIN (전부 살린다!)
SELECT A.REGIONID,
	-- B.REGIONID AS B_REGIONID,
	B.REGIONNAME,
	A.PRODUCT,
	A.YEARWEEK,
	A.QTY
FROM JOIN_KOPO_PRODUCT_VOLUME A
RIGHT JOIN JOIN_REGION_MASTER B
ON A.REGIONID = B.REGIONID
UNION 
SELECT A.REGIONID,
	-- B.REGIONID AS B_REGIONID,
	B.REGIONNAME,
	A.PRODUCT,
	A.YEARWEEK,
	A.QTY
FROM JOIN_KOPO_PRODUCT_VOLUME A
LEFT JOIN JOIN_REGION_MASTER B
ON A.REGIONID = B.REGIONID
ORDER BY REGIONID, PRODUCT, YEARWEEK


-- UNION 은 중복제거 한다
-- UNION ALL은 중복을 제거하지않고 그냥 붙입니다.
EXPLAIN ANALYZE
SELECT * 
FROM JOIN_KOPO_PRODUCT_VOLUME
-- AND REGIONID = 'A01'
UNION ALL
SELECT * 
FROM JOIN_KOPO_PRODUCT_VOLUME
-- AND REGIONID = 'A02'


SELECT REGION_NAME, 
	ACCOUNT_NAME, 
	COUNT(ACCOUNT_NAME)
FROM JOIN_BOMB_DATA1 
GROUP BY REGION_NAME, ACCOUNT_NAME

SELECT A.*,
	B.PROMOTION_ID,
	C.PROMOTION_TERM,
	C.PROMOTION_RATIO
FROM JOIN_BOMB_DATA1 A
LEFT JOIN JOIN_BOMB_DATA2 B
ON A.REGION_NAME = B.REGION_NAME
AND A.ACCOUNT_NAME = B.ACCOUNT_NAME
AND A.YEARWEEK = B.YEARWEEK
JOIN JOIN_BOMB_DATA3 C
ON B.PROMOTION_ID = C.PROMOTION_ID
-- 테이블의 컬럼별..!!! 테이블정의서 ~ 인터뷰

SELECT  *
FROM JOIN_BOMB_DATA2


SELECT  *
FROM JOIN_BOMB_DATA2




